"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import sys
import os
# import os # این خط تکراری بود، حذف شد
# from pathlib import Path # این خط هم تکراری بود، حذف شد

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# این BASE_DIR اولیه که اینجا تعریف شده، ریشه اصلی پروژه است (پوشه crypto-landing)
BASE_DIR = Path(__file__).resolve().parent.parent 

# این بخش برای اضافه کردن پوشه apps به PATH پایتون هست.
# این یعنی به پایتون می‌گیم که پوشه 'apps' هم جزو ماژول‌هایی هست که باید بگردی توش.
# این خط بسیار مهمه و ظاهراً درست هم تنظیم شده.
## sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# --- شروع تنظیمات اصلی ---

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-aqnsq&o7d@ci9=8w9xmsk59qy+8+x&9&l^!4rhf-=)0=x^iz9n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# این خط هم مهمه که به جنگو بگی مدل User سفارشی ما کجاست.
# با توجه به اینکه فایل apps.py رو درست تنظیم کردیم، این باید درست کار کنه.


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # کتابخانه‌های جانبی
    'rest_framework',
    'corsheaders',

    # اپلیکیشن‌های ما (حتماً از مسیر کامل استفاده کن)
    # این قسمت هم درسته، چون ما از AppConfig استفاده کردیم.
    'apps.users.apps.UsersConfig',
    'apps.trading.apps.TradingConfig',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # <--- این حتماً قبل از Auth باشه
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', # <--- این بعد از Session باشه
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'corsheaders.middleware.CorsMiddleware', # این رو هم اضافه کن اگه لازم داری
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates', # <--- این خط حیاتیه
        'DIRS': [], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
AUTH_USER_MODEL = 'users.User'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/ref/settings/#internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/ref/settings/#static-files

STATIC_URL = 'static/'
